from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# SELECT MODE
MODE="DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = False

# Find Cointegrated Pairs
FIND_COINTEGRATED=True

#Place Trades
PLACE_TRADES=True

#Resolution
RESOLUTION ="1HOUR"

#Stats Window
WINDOW = 21

#Thresholds - Opening
MAX_HALF_LIFE =24
ZSCORE_THRESH = 1.5
USD_PER_TRADE= 50
USD_MIN_COLLATERAL=1880

#Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS= True

#WALLET ADDY
ETHEREUM_ADDRESS="0xB41008f6968DF65282180B890B792c48Ed4c552c"


# WALLET PRIVATE KEY
ETH_PRIVATE_KEY=config("ETH_PRIVATE_KEY")
# STARK KEYS FOR DYDX TESTNET
STARK_PRIVATE_KEY_TESTNET=config("STARK_PRIVATE_KEY_TESTNET")
#DYDX API KEY, SECRET AND PASSPHRASE
DYDX_API_KEY_TESTNET=config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET=config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET=config("DYDX_API_PASSPHRASE_TESTNET")
#ETH NETWORK TESTNET
HOSTTEST=API_HOST_GOERLI
#ALCHEMY API URL TESTNET APP
alchemy_url_testapp = config("alchemy_url_testapp")

# STARK KEYS FOR DYDX MAINNET
STARK_PRIVATE_KEY_MAINNET=config("STARK_PRIVATE_KEY_MAINNET")
#DYDX API KEY, SECRET AND PASSPHRASE
DYDX_API_KEY_MAINNET=config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET=config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET=config("DYDX_API_PASSPHRASE_MAINNET")
#ETH NETWORK MAINNET
HOSTMAIN=API_HOST_MAINNET
#ALCHEMY API URL MAINNET APP
alchemy_url_mainapp = config("alchemy_url_mainapp")


#KEYS Export
STARK_PRIVATE_KEY= STARK_PRIVATE_KEY_MAINNET if MODE=="PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY= DYDX_API_KEY_MAINNET if MODE=="PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET= DYDX_API_SECRET_MAINNET if MODE=="PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE= DYDX_API_PASSPHRASE_MAINNET if MODE=="PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

#NETWORK PROVIDER
HTTP_PROVIDER=alchemy_url_mainapp if MODE=="PRODUCTION" else alchemy_url_testapp

#ETH NET
HOST=HOSTMAIN if MODE == "PRODUCTION" else HOSTTEST









